## Pytorch

In [9]:
import torch
import numpy as np

### Shape

In [1]:
X = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

In [4]:
t = torch.tensor(X)
t

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [5]:
type(t)

torch.Tensor

In [6]:
t.shape

torch.Size([3, 3])

In [7]:
t.reshape(1, 9)

tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [8]:
t.reshape(1, 9).shape

torch.Size([1, 9])

### Attributes

In [10]:
print(t.dtype)
print(t.device)
print(t.layout)

torch.int64
cpu
torch.strided


### Creation

In [11]:
data = np.array([1, 2, 3])

In [23]:
t1 = torch.Tensor(data)

In [24]:
# Accepts data type
# Copies data
t2 = torch.tensor(data, dtype=torch.float32)

In [28]:
# Shares memory
# Accepts Python structures
t3 = torch.as_tensor(data)

In [26]:
t4 = torch.from_numpy(data)

In [27]:
print(t1)
print(t2)
print(t3)
print(t4)

tensor([1., 2., 3.])
tensor([1., 2., 3.])
tensor([1, 2, 3], dtype=torch.int32)
tensor([1, 2, 3], dtype=torch.int32)


In [29]:
t1.numel()

3

### Creation without data

In [13]:
torch.eye(2)

tensor([[1., 0.],
        [0., 1.]])

In [14]:
torch.zeros(2, 2)

tensor([[0., 0.],
        [0., 0.]])

In [15]:
torch.ones(2, 2)

tensor([[1., 1.],
        [1., 1.]])

In [16]:
torch.rand(2, 2)

tensor([[0.1055, 0.5846],
        [0.1002, 0.2763]])

In [18]:
torch.get_default_dtype()

torch.float32

### Squeezing

In [30]:
X = np.array([[5, 1, 3],
             [3, 0, 1]])

In [33]:
t = torch.tensor(X)
print(t)
print(t.shape)

tensor([[5, 1, 3],
        [3, 0, 1]], dtype=torch.int32)
torch.Size([2, 3])


In [34]:
# Reshape
t.reshape(1, 6)

tensor([[5, 1, 3, 3, 0, 1]], dtype=torch.int32)

In [35]:
# Squeeze
t.reshape(1, 6).squeeze()

tensor([5, 1, 3, 3, 0, 1], dtype=torch.int32)

### Flatten

In [36]:
def flatten(t):
    t = t.reshape(1, -1)
    t = t.squeeze()
    return t

In [37]:
flatten(t)

tensor([5, 1, 3, 3, 0, 1], dtype=torch.int32)

In [38]:
t1 = torch.tensor([
    [1, 1, 1, 1],
    [2, 2, 2, 2],
    [3, 3, 3, 3],
    [4, 4, 4, 4]
])
t2 = torch.tensor([
    [1, 1, 1, 1],
    [2, 2, 2, 2],
    [3, 3, 3, 3],
    [4, 4, 4, 4]
])

In [41]:
t3 = torch.stack((t1, t2))
t3

tensor([[[1, 1, 1, 1],
         [2, 2, 2, 2],
         [3, 3, 3, 3],
         [4, 4, 4, 4]],

        [[1, 1, 1, 1],
         [2, 2, 2, 2],
         [3, 3, 3, 3],
         [4, 4, 4, 4]]])

In [43]:
t3[0][0][0]

tensor(1)

In [46]:
t3.flatten(start_dim=1)

tensor([[1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 4],
        [1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 4]])

### Broadcasting and operations

In [47]:
t1 + t2

tensor([[2, 2, 2, 2],
        [4, 4, 4, 4],
        [6, 6, 6, 6],
        [8, 8, 8, 8]])

In [48]:
t1 - t2

tensor([[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]])

In [49]:
t1 * t2

tensor([[ 1,  1,  1,  1],
        [ 4,  4,  4,  4],
        [ 9,  9,  9,  9],
        [16, 16, 16, 16]])

In [50]:
t1 / t2

tensor([[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]])

In [51]:
t2 * 2

tensor([[2, 2, 2, 2],
        [4, 4, 4, 4],
        [6, 6, 6, 6],
        [8, 8, 8, 8]])

In [52]:
t2.add(2)

tensor([[3, 3, 3, 3],
        [4, 4, 4, 4],
        [5, 5, 5, 5],
        [6, 6, 6, 6]])