## Pytorch

In [21]:
import torch
import numpy as np


### Shape

In [1]:
X = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

In [4]:
t = torch.tensor(X)
t

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [5]:
type(t)

torch.Tensor

In [6]:
t.shape

torch.Size([3, 3])

In [7]:
t.reshape(1, 9)

tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [8]:
t.reshape(1, 9).shape

torch.Size([1, 9])

### Attributes

In [10]:
print(t.dtype)
print(t.device)
print(t.layout)

torch.int64
cpu
torch.strided


### Creation

In [11]:
data = np.array([1, 2, 3])

In [23]:
t1 = torch.Tensor(data)

In [24]:
# Accepts data type
# Copies data
t2 = torch.tensor(data, dtype=torch.float32)

In [28]:
# Shares memory
# Accepts Python structures
t3 = torch.as_tensor(data)

In [26]:
t4 = torch.from_numpy(data)

In [27]:
print(t1)
print(t2)
print(t3)
print(t4)

tensor([1., 2., 3.])
tensor([1., 2., 3.])
tensor([1, 2, 3], dtype=torch.int32)
tensor([1, 2, 3], dtype=torch.int32)


In [29]:
t1.numel()

3

### Creation without data

In [13]:
torch.eye(2)

tensor([[1., 0.],
        [0., 1.]])

In [14]:
torch.zeros(2, 2)

tensor([[0., 0.],
        [0., 0.]])

In [15]:
torch.ones(2, 2)

tensor([[1., 1.],
        [1., 1.]])

In [16]:
torch.rand(2, 2)

tensor([[0.1055, 0.5846],
        [0.1002, 0.2763]])

In [18]:
torch.get_default_dtype()

torch.float32

### Squeezing

In [30]:
X = np.array([[5, 1, 3],
             [3, 0, 1]])

In [33]:
t = torch.tensor(X)
print(t)
print(t.shape)

tensor([[5, 1, 3],
        [3, 0, 1]], dtype=torch.int32)
torch.Size([2, 3])


In [34]:
# Reshape
t.reshape(1, 6)

tensor([[5, 1, 3, 3, 0, 1]], dtype=torch.int32)

In [35]:
# Squeeze
t.reshape(1, 6).squeeze()

tensor([5, 1, 3, 3, 0, 1], dtype=torch.int32)

### Flatten

In [36]:
def flatten(t):
    t = t.reshape(1, -1)
    t = t.squeeze()
    return t

In [37]:
flatten(t)

tensor([5, 1, 3, 3, 0, 1], dtype=torch.int32)

In [11]:
t1 = torch.tensor([
    [1, 1, 1, 1],
    [2, 2, 2, 2],
    [3, 3, 3, 3],
    [4, 4, 4, 4]
], dtype=torch.float32)
t2 = torch.tensor([
    [1, 1, 1, 1],
    [2, 2, 2, 2],
    [3, 3, 3, 3],
    [4, 4, 4, 4]
])

In [41]:
t3 = torch.stack((t1, t2))
t3

tensor([[[1, 1, 1, 1],
         [2, 2, 2, 2],
         [3, 3, 3, 3],
         [4, 4, 4, 4]],

        [[1, 1, 1, 1],
         [2, 2, 2, 2],
         [3, 3, 3, 3],
         [4, 4, 4, 4]]])

In [43]:
t3[0][0][0]

tensor(1)

In [46]:
t3.flatten(start_dim=1)

tensor([[1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 4],
        [1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 4]])

### Broadcasting and operations

In [47]:
t1 + t2

tensor([[2, 2, 2, 2],
        [4, 4, 4, 4],
        [6, 6, 6, 6],
        [8, 8, 8, 8]])

In [48]:
t1 - t2

tensor([[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]])

In [49]:
t1 * t2

tensor([[ 1,  1,  1,  1],
        [ 4,  4,  4,  4],
        [ 9,  9,  9,  9],
        [16, 16, 16, 16]])

In [50]:
t1 / t2

tensor([[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]])

In [51]:
t2 * 2

tensor([[2, 2, 2, 2],
        [4, 4, 4, 4],
        [6, 6, 6, 6],
        [8, 8, 8, 8]])

In [52]:
t2.add(2)

tensor([[3, 3, 3, 3],
        [4, 4, 4, 4],
        [5, 5, 5, 5],
        [6, 6, 6, 6]])

In [4]:
y1 = np.array([2, 3])
y2 = np.array([[2, 3],
              [1, 4]])

In [5]:
np.broadcast_to(y1, y2.shape)

array([[2, 3],
       [2, 3]])

### Comparison

In [8]:
t1.eq(1)

tensor([[ True,  True,  True,  True],
        [False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [12]:
t1.sqrt()

tensor([[1.0000, 1.0000, 1.0000, 1.0000],
        [1.4142, 1.4142, 1.4142, 1.4142],
        [1.7321, 1.7321, 1.7321, 1.7321],
        [2.0000, 2.0000, 2.0000, 2.0000]])

### Reduction operations

In [13]:
t = torch.tensor([[0, 1, 0],
                 [2, 0, 2],
                  [0, 3, 0]], dtype=torch.float32)

In [14]:
t.sum()

tensor(8.)

In [15]:
t.mean()

tensor(0.8889)

In [20]:
t.std().item()

1.1666666269302368

In [18]:
t.sum(dim=1)

tensor([1., 4., 3.])

In [19]:
t.argmax()

tensor(7)

### Network

In [22]:
import torch.nn as nn

In [30]:
class Network(nn.Module):
    def __init__(self):
        super(Network, self).__init__()
        
        self.conv1 = nn.Conv2d(in_channels=1, out_channels=6, kernel_size=5)
        self.conv2 = nn.Conv2d(in_channels=6, out_channels=12, kernel_size=5)
        
        self.fc1 = nn.Linear(in_features=12*4*4, out_features=120)
        self.fc2 = nn.Linear(in_features=120, out_features=60)
        self.out = nn.Linear(in_features=60, out_features=10)
        
        def forward(self, t):
            
            return t

In [31]:
network = Network()

In [32]:
print(network)

Network(
  (conv1): Conv2d(1, 6, kernel_size=(5, 5), stride=(1, 1))
  (conv2): Conv2d(6, 12, kernel_size=(5, 5), stride=(1, 1))
  (fc1): Linear(in_features=192, out_features=120, bias=True)
  (fc2): Linear(in_features=120, out_features=60, bias=True)
  (out): Linear(in_features=60, out_features=10, bias=True)
)


In [34]:
network.conv1.weight

Parameter containing:
tensor([[[[ 0.1130, -0.0030,  0.0492,  0.0278,  0.0909],
          [-0.0902, -0.0655, -0.0683,  0.1963,  0.1364],
          [-0.1949, -0.1374,  0.0641, -0.0890, -0.1998],
          [ 0.1470, -0.0045, -0.0469,  0.1053,  0.0437],
          [-0.0014, -0.1062,  0.1603,  0.1175, -0.1300]]],


        [[[ 0.0040, -0.1977, -0.1698,  0.1244,  0.0509],
          [-0.1454,  0.1325, -0.1850, -0.0592,  0.1583],
          [-0.1620, -0.1555,  0.1054, -0.0825,  0.1456],
          [-0.0422, -0.1182,  0.1099, -0.0191, -0.1564],
          [-0.1095, -0.0702, -0.1136,  0.0586,  0.0519]]],


        [[[-0.0423,  0.1807, -0.0411,  0.0917, -0.1442],
          [-0.0187, -0.0986, -0.0356, -0.1687, -0.0510],
          [-0.1895, -0.1998,  0.1613, -0.0331, -0.0358],
          [-0.1549,  0.0203,  0.0364,  0.0447,  0.1237],
          [-0.1915,  0.1006,  0.1660, -0.0588, -0.1506]]],


        [[[-0.0873, -0.0838,  0.1150, -0.1667, -0.0746],
          [ 0.1932, -0.0309,  0.0230,  0.1129,  0.1824

In [35]:
network.conv1.weight.shape

torch.Size([6, 1, 5, 5])